use std::env;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Clone, Copy)]
enum PythonNodeDeclFormat {
    Decorator,
}

struct PythonNodeFile {
    relative_path: String,
    format: PythonNodeDeclFormat,
    type_id: String,
    title: String,
    category: String,
    inputs: Vec<PythonPinSpec>,
    outputs: Vec<PythonPinSpec>,
    params: Vec<PythonParamSpec>,
}

struct PythonPinSpec {
    name: String,
    data_type: String,
    required: bool,
}

struct PythonParamSpec {
    name: String,
    data_type: String,
    default_expr: String,
    min_expr: Option<String>,
    max_expr: Option<String>,
    options_expr: Vec<String>,
    widget_expr: Option<String>,
    expose_expr: Vec<String>,
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=../python/nodes");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let python_nodes_dir = manifest_dir.join("../python/nodes");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let generated_path = out_dir.join("python_nodes_generated.rs");
    let inventory_generated_path = out_dir.join("python_nodes_inventory.rs");

    let node_files = scan_python_nodes(&python_nodes_dir);
    let generated = render_generated_file(&node_files);
    let inventory_generated = render_inventory_generated_file(&node_files);

    fs::write(&generated_path, generated).expect("write python_nodes_generated.rs");
    fs::write(&inventory_generated_path, inventory_generated)
        .expect("write python_nodes_inventory.rs");
}

fn scan_python_nodes(dir: &Path) -> Vec<PythonNodeFile> {
    let entries =
        fs::read_dir(dir).unwrap_or_else(|err| panic!("read python nodes dir failed: {err}"));
    let mut files = Vec::new();

    for entry in entries {
        let entry = entry.unwrap_or_else(|err| panic!("read python node entry failed: {err}"));
        let path = entry.path();

        if !path.is_file() {
            continue;
        }

        if path.extension().and_then(|ext| ext.to_str()) != Some("py") {
            continue;
        }

        if path.file_name().and_then(|name| name.to_str()) == Some("__init__.py") {
            continue;
        }

        let source = fs::read_to_string(&path).unwrap_or_else(|err| {
            panic!("read python node file '{}' failed: {err}", path.display())
        });

        let format = detect_decl_format(&path, &source);
        let relative_path = path
            .strip_prefix(dir.parent().unwrap_or(dir))
            .unwrap_or(&path)
            .to_string_lossy()
            .replace('\\', "/");
        let type_id = extract_type_id(&path, &source, format);
        let title = extract_title(&path, &source, format);
        let category = extract_category(&path, &source, format);
        let inputs = extract_pins(&path, &source, "inputs", true, format);
        let outputs = extract_pins(&path, &source, "outputs", false, format);
        let params = extract_params(&path, &source, format);

        validate_node_decl(&path, &inputs, &outputs, &params);

        files.push(PythonNodeFile {
            relative_path,
            format,
            type_id,
            title,
            category,
            inputs,
            outputs,
            params,
        });
    }

    files.sort_by(|a, b| a.relative_path.cmp(&b.relative_path));
    files
}

fn detect_decl_format(path: &Path, source: &str) -> PythonNodeDeclFormat {
    if source.contains("@node(") {
        PythonNodeDeclFormat::Decorator
    } else {
        panic!(
            "python node file '{}' does not match supported declaration format: @node(...)",
            path.display()
        );
    }
}

fn render_generated_file(files: &[PythonNodeFile]) -> String {
    let mut out = String::from("// @generated by engine/build.rs\n");
    out.push_str("pub static PYTHON_NODE_DECL_SPECS: &[PythonNodeDeclSpec] = &[\n");

    for file in files {
        let format = match file.format {
            PythonNodeDeclFormat::Decorator => "PythonNodeDeclFormat::Decorator",
        };

        out.push_str(&format!(
            "    PythonNodeDeclSpec {{ path: {:?}, format: {}, type_id: {:?}, title: {:?}, category: {:?}, inputs: &[{}], outputs: &[{}], params: &[{}] }},\n",
            file.relative_path,
            format,
            file.type_id,
            file.title,
            file.category,
            render_pin_specs(&file.inputs),
            render_pin_specs(&file.outputs),
            render_param_specs(&file.params)
        ));
    }

    out.push_str("];\n");
    out
}

fn render_inventory_generated_file(files: &[PythonNodeFile]) -> String {
    let mut out = String::from("// @generated by engine/build.rs\n");

    for file in files {
        out.push_str("inventory::submit!(crate::node_manager::NodeDefEntry(|| {\n");
        out.push_str("    crate::node_manager::NodeDef {\n");
        out.push_str(&format!("        type_id: {:?}.into(),\n", file.type_id));
        out.push_str(&format!("        name: {:?}.into(),\n", file.title));
        out.push_str(&format!("        category: {:?}.into(),\n", file.category));
        out.push_str(&format!(
            "        inputs: vec![{}],\n",
            render_inventory_pins(&file.inputs, true)
        ));
        out.push_str(&format!(
            "        outputs: vec![{}],\n",
            render_inventory_pins(&file.outputs, false)
        ));
        out.push_str(&format!(
            "        params: vec![{}],\n",
            render_inventory_params(&file.params)
        ));
        out.push_str(&format!(
            "        execute: Box::new(|_ctx, _inputs| Box::pin(async move {{ Err(Box::<dyn std::error::Error + Send + Sync>::from(format!(\"python node '{}' is declaration-only in the local engine runtime\"))) }})),\n",
            file.type_id
        ));
        out.push_str("    }\n");
        out.push_str("}));\n");
    }

    out
}

fn extract_type_id(path: &Path, source: &str, format: PythonNodeDeclFormat) -> String {
    match format {
        PythonNodeDeclFormat::Decorator => extract_named_string(path, source, "type_id")
            .unwrap_or_else(|| panic!("missing type_id in decorator node '{}'", path.display())),
    }
}

fn extract_title(path: &Path, source: &str, format: PythonNodeDeclFormat) -> String {
    match format {
        PythonNodeDeclFormat::Decorator => extract_named_string(path, source, "title")
            .unwrap_or_else(|| panic!("missing title in decorator node '{}'", path.display())),
    }
}

fn extract_category(path: &Path, source: &str, format: PythonNodeDeclFormat) -> String {
    match format {
        PythonNodeDeclFormat::Decorator => extract_named_string(path, source, "category")
            .unwrap_or_else(|| panic!("missing category in decorator node '{}'", path.display())),
    }
}

fn extract_pins(
    path: &Path,
    source: &str,
    field: &str,
    default_required: bool,
    format: PythonNodeDeclFormat,
) -> Vec<PythonPinSpec> {
    match format {
        PythonNodeDeclFormat::Decorator => {
            let block = extract_list_block(path, source, field);
            parse_decorator_pins(&block, default_required)
        }
    }
}

fn extract_params(path: &Path, source: &str, format: PythonNodeDeclFormat) -> Vec<PythonParamSpec> {
    match format {
        PythonNodeDeclFormat::Decorator => {
            let block = extract_list_block(path, source, "params");
            parse_decorator_params(&block)
        }
    }
}

fn extract_named_string(path: &Path, source: &str, field: &str) -> Option<String> {
    let needle = format!("{}=\"", field);
    let start = source.find(&needle)? + needle.len();
    let rest = &source[start..];
    let end = rest.find('"').unwrap_or_else(|| {
        panic!(
            "unterminated string for field '{}' in '{}'",
            field,
            path.display()
        )
    });
    Some(rest[..end].to_string())
}

fn extract_list_block(path: &Path, source: &str, field: &str) -> String {
    let needle = format!("{}=[", field);
    let start = source
        .find(&needle)
        .unwrap_or_else(|| panic!("missing list field '{}' in '{}'", field, path.display()));
    let after = &source[start + needle.len()..];
    let mut depth = 1usize;
    let mut end_idx = None;

    for (idx, ch) in after.char_indices() {
        match ch {
            '[' => depth += 1,
            ']' => {
                depth -= 1;
                if depth == 0 {
                    end_idx = Some(idx);
                    break;
                }
            }
            _ => {}
        }
    }

    let end = end_idx.unwrap_or_else(|| {
        panic!(
            "unterminated list field '{}' in '{}'",
            field,
            path.display()
        )
    });

    after[..end].to_string()
}

fn parse_decorator_pins(block: &str, default_required: bool) -> Vec<PythonPinSpec> {
    let mut pins = Vec::new();

    for raw in split_top_level_items(block) {
        let item = raw.trim();
        if item.is_empty() {
            continue;
        }
        let args = extract_call_args(item, "Pin");
        let positional = extract_string_literals(&args);
        if positional.len() < 2 {
            continue;
        }
        if !default_required && args.contains("required=") {
            panic!("output Pin(...) must not declare 'required'");
        }
        let required = extract_bool_kwarg(&args, "required").unwrap_or(default_required);
        pins.push(PythonPinSpec {
            name: positional[0].clone(),
            data_type: positional[1].clone(),
            required,
        });
    }

    pins
}

fn parse_decorator_params(block: &str) -> Vec<PythonParamSpec> {
    let mut params = Vec::new();

    for raw in split_top_level_items(block) {
        let item = raw.trim();
        if item.is_empty() {
            continue;
        }
        let args = extract_call_args(item, "Param");
        let positional = extract_string_literals(&args);
        if positional.len() < 2 {
            continue;
        }
        let default_expr = extract_default_expr(&args).unwrap_or_else(|| "None".into());
        params.push(PythonParamSpec {
            name: positional[0].clone(),
            data_type: positional[1].clone(),
            default_expr,
            min_expr: extract_named_expr(&args, "min"),
            max_expr: extract_named_expr(&args, "max"),
            options_expr: extract_options_expr(&args),
            widget_expr: extract_named_expr(&args, "widget"),
            expose_expr: extract_expose_exprs(&args),
        });
    }

    params
}

fn validate_node_decl(
    path: &Path,
    inputs: &[PythonPinSpec],
    outputs: &[PythonPinSpec],
    params: &[PythonParamSpec],
) {
    validate_unique_names(path, inputs, outputs, params);
    validate_param_rules(path, params);
}

fn validate_unique_names(
    path: &Path,
    inputs: &[PythonPinSpec],
    outputs: &[PythonPinSpec],
    params: &[PythonParamSpec],
) {
    use std::collections::HashSet;

    let mut input_names = HashSet::new();
    let mut output_names = HashSet::new();

    for name in inputs.iter().map(|p| &p.name) {
        if !input_names.insert(name.clone()) {
            panic!(
                "duplicate input interface name '{}' in '{}'",
                name,
                path.display()
            );
        }
    }
    for name in outputs.iter().map(|p| &p.name) {
        if !output_names.insert(name.clone()) {
            panic!(
                "duplicate output interface name '{}' in '{}'",
                name,
                path.display()
            );
        }
    }

    for param in params {
        let expose_values = parse_string_list_literal_from_exprs(&param.expose_expr);

        if expose_values.iter().any(|value| value == "input")
            && !input_names.insert(param.name.clone())
        {
            panic!(
                "duplicate input-side interface name '{}' in '{}'",
                param.name,
                path.display()
            );
        }

        if expose_values.iter().any(|value| value == "output")
            && !output_names.insert(param.name.clone())
        {
            panic!(
                "duplicate output-side interface name '{}' in '{}'",
                param.name,
                path.display()
            );
        }
    }
}

fn validate_param_rules(path: &Path, params: &[PythonParamSpec]) {
    for param in params {
        if param.expose_expr.is_empty() {
            panic!(
                "Param '{}' in '{}' must declare non-empty expose=[...]",
                param.name,
                path.display()
            );
        }

        let expose_values = parse_string_list_literal_from_exprs(&param.expose_expr);
        if expose_values.is_empty() {
            panic!(
                "Param '{}' in '{}' must declare at least one valid expose value",
                param.name,
                path.display()
            );
        }

        for value in &expose_values {
            match value.as_str() {
                "control" | "input" | "output" => {}
                other => panic!(
                    "Param '{}' in '{}' has unsupported expose value '{}'",
                    param.name,
                    path.display(),
                    other
                ),
            }
        }

        if is_complex_python_type(&param.data_type) && param.default_expr.trim() != "None" {
            panic!(
                "Param '{}' in '{}' with complex type '{}' must use default=None",
                param.name,
                path.display(),
                param.data_type
            );
        }
    }
}

fn is_complex_python_type(data_type: &str) -> bool {
    matches!(
        data_type,
        "IMAGE" | "MASK" | "MODEL" | "CLIP" | "VAE" | "LATENT" | "CONDITIONING"
    )
}

fn split_top_level_items(block: &str) -> Vec<String> {
    let mut items = Vec::new();
    let mut current = String::new();
    let mut paren_depth = 0usize;
    let mut bracket_depth = 0usize;

    for ch in block.chars() {
        match ch {
            '(' => {
                paren_depth += 1;
                current.push(ch);
            }
            ')' => {
                paren_depth = paren_depth.saturating_sub(1);
                current.push(ch);
            }
            '[' => {
                bracket_depth += 1;
                current.push(ch);
            }
            ']' => {
                bracket_depth = bracket_depth.saturating_sub(1);
                current.push(ch);
            }
            ',' if paren_depth == 0 && bracket_depth == 0 => {
                let trimmed = current.trim();
                if !trimmed.is_empty() {
                    items.push(trimmed.to_string());
                }
                current.clear();
            }
            _ => current.push(ch),
        }
    }

    let trimmed = current.trim();
    if !trimmed.is_empty() {
        items.push(trimmed.to_string());
    }

    items
}

fn extract_call_args<'a>(item: &'a str, func: &str) -> &'a str {
    let prefix = format!("{}(", func);
    let item = item.trim();
    if !item.starts_with(&prefix) || !item.ends_with(')') {
        panic!("unsupported legacy declaration item: '{}'", item);
    }
    &item[prefix.len()..item.len() - 1]
}

fn extract_string_literals(args: &str) -> Vec<String> {
    let mut values = Vec::new();
    let chars: Vec<char> = args.chars().collect();
    let mut i = 0usize;
    while i < chars.len() {
        if chars[i] == '"' {
            let start = i + 1;
            i += 1;
            while i < chars.len() && chars[i] != '"' {
                i += 1;
            }
            if i < chars.len() {
                values.push(chars[start..i].iter().collect());
            }
        }
        i += 1;
    }
    values
}

fn extract_bool_kwarg(args: &str, key: &str) -> Option<bool> {
    let needle = format!("{}=", key);
    let start = args.find(&needle)? + needle.len();
    let rest = &args[start..];
    if rest.starts_with("True") {
        Some(true)
    } else if rest.starts_with("False") {
        Some(false)
    } else {
        None
    }
}

fn extract_default_expr(args: &str) -> Option<String> {
    extract_named_expr(args, "default")
}

fn extract_named_expr(args: &str, key: &str) -> Option<String> {
    let needle = format!("{}=", key);
    let start = args.find(&needle)? + needle.len();
    let rest = &args[start..];
    let mut end = rest.len();
    let mut depth = 0usize;
    for (idx, ch) in rest.char_indices() {
        match ch {
            '[' | '(' => depth += 1,
            ']' | ')' => depth = depth.saturating_sub(1),
            ',' if depth == 0 => {
                end = idx;
                break;
            }
            _ => {}
        }
    }
    Some(rest[..end].trim().to_string())
}

fn extract_options_expr(args: &str) -> Vec<String> {
    extract_named_expr(args, "options")
        .map(|expr| vec![expr])
        .unwrap_or_default()
}

fn extract_expose_exprs(args: &str) -> Vec<String> {
    extract_named_expr(args, "expose")
        .map(|expr| vec![expr])
        .unwrap_or_default()
}

fn render_pin_specs(pins: &[PythonPinSpec]) -> String {
    pins.iter()
        .map(|pin| {
            format!(
                "PythonPinDeclSpec {{ name: {:?}, data_type: {:?}, required: {} }}",
                pin.name, pin.data_type, pin.required
            )
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn render_param_specs(params: &[PythonParamSpec]) -> String {
    params
        .iter()
        .map(|param| {
            let min_expr = match &param.min_expr {
                Some(value) => format!("Some({:?})", value),
                None => "None".to_string(),
            };
            let max_expr = match &param.max_expr {
                Some(value) => format!("Some({:?})", value),
                None => "None".to_string(),
            };
            let widget_expr = match &param.widget_expr {
                Some(value) => format!("Some({:?})", value),
                None => "None".to_string(),
            };
            let options_expr = param
                .options_expr
                .iter()
                .map(|value| format!("{:?}", value))
                .collect::<Vec<_>>()
                .join(", ");
            let expose_expr = param
                .expose_expr
                .iter()
                .map(|value| format!("{:?}", value))
                .collect::<Vec<_>>()
                .join(", ");
            format!(
                "PythonParamDeclSpec {{ name: {:?}, data_type: {:?}, default_expr: {:?}, min_expr: {}, max_expr: {}, options_expr: &[{}], widget_expr: {}, expose_expr: &[{}] }}",
                param.name,
                param.data_type,
                param.default_expr,
                min_expr,
                max_expr,
                options_expr,
                widget_expr,
                expose_expr
            )
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn render_inventory_pins(pins: &[PythonPinSpec], input: bool) -> String {
    pins.iter()
        .map(|pin| {
            format!(
                "crate::node_manager::PinDef {{ name: {:?}.into(), data_type: {}, optional: {} }}",
                pin.name,
                render_data_type_expr(&pin.data_type),
                if input {
                    (!pin.required).to_string()
                } else {
                    "false".to_string()
                }
            )
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn render_inventory_params(params: &[PythonParamSpec]) -> String {
    params
        .iter()
        .map(|param| {
            format!(
                "crate::node_manager::ParamDef {{ name: {:?}.into(), data_type: {}, constraint: {}, default_value: {}, expose: vec![{}] }}",
                param.name,
                render_param_data_type_expr(&param.data_type),
                render_constraint_expr(param),
                render_default_value_expr(&param.data_type, &param.default_expr),
                render_param_expose_expr(param)
            )
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn render_param_data_type_expr(data_type: &str) -> String {
    match data_type {
        "ENUM" => "types::DataType::string()".into(),
        other => render_data_type_expr(other),
    }
}

fn render_data_type_expr(data_type: &str) -> String {
    match data_type {
        "IMAGE" => "types::DataType::image()".into(),
        "FLOAT" => "types::DataType::float()".into(),
        "INT" => "types::DataType::int()".into(),
        "BOOL" => "types::DataType::bool()".into(),
        "STRING" => "types::DataType::string()".into(),
        "MODEL" => "types::DataType(\"ai.model\".into())".into(),
        "CLIP" => "types::DataType(\"ai.clip\".into())".into(),
        "VAE" => "types::DataType(\"ai.vae\".into())".into(),
        "LATENT" => "types::DataType(\"ai.latent\".into())".into(),
        "CONDITIONING" => "types::DataType(\"ai.conditioning\".into())".into(),
        "MASK" => "types::DataType(\"mask\".into())".into(),
        other => format!("types::DataType({:?}.into())", other.to_ascii_lowercase()),
    }
}

fn render_default_value_expr(data_type: &str, default_expr: &str) -> String {
    let expr = default_expr.trim();
    if expr == "None" {
        return match data_type {
            "FLOAT" => "types::Value::Float(0.0)".into(),
            "INT" => "types::Value::Int(0)".into(),
            "BOOL" => "types::Value::Bool(false)".into(),
            _ => "types::Value::String(String::new())".into(),
        };
    }

    match data_type {
        "FLOAT" => format!("types::Value::Float({})", expr),
        "INT" => format!("types::Value::Int({})", expr),
        "BOOL" => match expr {
            "True" => "types::Value::Bool(true)".into(),
            "False" => "types::Value::Bool(false)".into(),
            _ => panic!("invalid bool default expression '{}'", expr),
        },
        _ => format!(
            "types::Value::String({:?}.into())",
            parse_python_string_literal(expr)
        ),
    }
}

fn render_constraint_expr(param: &PythonParamSpec) -> String {
    if param.data_type == "ENUM" || !param.options_expr.is_empty() {
        let options = param
            .options_expr
            .iter()
            .flat_map(|expr| parse_string_list_literal(expr))
            .map(|value| format!("{:?}.to_string()", value))
            .collect::<Vec<_>>()
            .join(", ");
        if options.is_empty() {
            return "None".into();
        }
        return format!("Some(types::Constraint::enum_options(vec![{}]))", options);
    }

    if let (Some(min), Some(max)) = (&param.min_expr, &param.max_expr) {
        return format!("Some(types::Constraint::range({}f64, {}f64))", min, max);
    }

    if param.widget_expr.as_deref() == Some("\"file_picker\"") {
        return "Some(types::Constraint::file_path(Vec::new()))".into();
    }

    "None".into()
}

fn render_param_expose_expr(param: &PythonParamSpec) -> String {
    let expose_values = if param.expose_expr.is_empty() {
        vec!["crate::node_manager::ParamExpose::Control".to_string()]
    } else {
        param
            .expose_expr
            .iter()
            .flat_map(|expr| parse_string_list_literal(expr))
            .filter_map(|value| match value.as_str() {
                "control" => Some("crate::node_manager::ParamExpose::Control".to_string()),
                "input" => Some("crate::node_manager::ParamExpose::Input".to_string()),
                "output" => Some("crate::node_manager::ParamExpose::Output".to_string()),
                _ => None,
            })
            .collect::<Vec<_>>()
    };

    expose_values.join(", ")
}

fn parse_python_string_literal(expr: &str) -> String {
    let trimmed = expr.trim();
    if trimmed.len() >= 2 && trimmed.starts_with('"') && trimmed.ends_with('"') {
        trimmed[1..trimmed.len() - 1].to_string()
    } else {
        trimmed.to_string()
    }
}

fn parse_string_list_literal(expr: &str) -> Vec<String> {
    let trimmed = expr.trim();
    if !(trimmed.starts_with('[') && trimmed.ends_with(']')) {
        return Vec::new();
    }

    let inner = &trimmed[1..trimmed.len() - 1];
    inner
        .split(',')
        .map(str::trim)
        .filter(|item| !item.is_empty())
        .map(parse_python_string_literal)
        .collect()
}

fn parse_string_list_literal_from_exprs(exprs: &[String]) -> Vec<String> {
    exprs
        .iter()
        .flat_map(|expr| parse_string_list_literal(expr))
        .collect()
}
