use crate::tree::Desc;
use crate::widget::props::WidgetProps;
use std::borrow::Cow;

/// Widget node descriptor.
///
/// `WidgetBuild.children` are generated by the widget itself. `WidgetDesc.children`
/// are supplied by the caller for wrapper widgets such as surfaces and panels.
pub struct WidgetDesc {
    id: Cow<'static, str>,
    props: Box<dyn WidgetProps>,
    children: Vec<Desc>,
}

impl Clone for WidgetDesc {
    fn clone(&self) -> Self {
        Self {
            id: self.id.clone(),
            props: self.props.clone_box(),
            children: self.children.clone(),
        }
    }
}

impl WidgetDesc {
    pub fn new(id: impl Into<Cow<'static, str>>, props: impl WidgetProps) -> Self {
        Self {
            id: id.into(),
            props: Box::new(props),
            children: Vec::new(),
        }
    }

    pub fn with_children(
        id: impl Into<Cow<'static, str>>,
        props: impl WidgetProps,
        children: Vec<Desc>,
    ) -> Self {
        Self {
            id: id.into(),
            props: Box::new(props),
            children,
        }
    }

    pub fn from_boxed(
        id: impl Into<Cow<'static, str>>,
        props: Box<dyn WidgetProps>,
        children: Vec<Desc>,
    ) -> Self {
        Self {
            id: id.into(),
            props,
            children,
        }
    }

    pub fn id(&self) -> &str {
        self.id.as_ref()
    }

    pub fn props(&self) -> &dyn WidgetProps {
        self.props.as_ref()
    }

    pub fn children(&self) -> &[Desc] {
        &self.children
    }

    pub fn into_parts(self) -> (Cow<'static, str>, Box<dyn WidgetProps>, Vec<Desc>) {
        (self.id, self.props, self.children)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::renderer::Color;
    use crate::widget::atoms::dot::DotProps;

    #[test]
    fn widget_desc_new_has_no_external_children() {
        let desc = WidgetDesc::new(
            "dot",
            DotProps {
                diameter: 10.0,
                fill: Color::WHITE,
                border: None,
                hittable: false,
                gestures: Vec::new(),
            },
        );

        assert_eq!(desc.id(), "dot");
        assert!(desc.children().is_empty());
    }

    #[test]
    fn widget_desc_with_children_keeps_external_children() {
        let desc = WidgetDesc::with_children(
            "dot",
            DotProps {
                diameter: 10.0,
                fill: Color::WHITE,
                border: None,
                hittable: false,
                gestures: Vec::new(),
            },
            vec![Desc::Leaf {
                id: Cow::Borrowed("dot::child"),
                style: Default::default(),
                kind: crate::tree::layout::LeafKind::Text {
                    content: "child".to_string(),
                    style: crate::renderer::TextStyle::new(Color::WHITE, 12.0),
                    layout: Default::default(),
                },
            }],
        );

        assert_eq!(desc.children().len(), 1);
    }
}
