use std::collections::HashSet;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

struct IconFile {
    id: String,
    file_name: String,
    const_name: String,
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let icons_dir = manifest_dir.join("../assets/icons");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", icons_dir.display());

    let icons = scan_icons(&icons_dir);
    for icon in &icons {
        println!(
            "cargo:rerun-if-changed={}",
            icons_dir.join(&icon.file_name).display()
        );
    }

    fs::write(
        out_dir.join("icon_assets_generated.rs"),
        render_asset_table(&icons),
    )
    .expect("write icon_assets_generated.rs");
    fs::write(
        out_dir.join("icon_names_generated.rs"),
        render_name_constants(&icons),
    )
    .expect("write icon_names_generated.rs");
}

fn scan_icons(icons_dir: &Path) -> Vec<IconFile> {
    let entries =
        fs::read_dir(icons_dir).unwrap_or_else(|err| panic!("read icons dir failed: {err}"));
    let mut icons = Vec::new();
    let mut const_names = HashSet::new();

    for entry in entries {
        let entry = entry.unwrap_or_else(|err| panic!("read icon entry failed: {err}"));
        let path = entry.path();
        if !path.is_file() || path.extension().and_then(|ext| ext.to_str()) != Some("svg") {
            continue;
        }

        let file_name = path
            .file_name()
            .and_then(|name| name.to_str())
            .unwrap_or_else(|| panic!("icon file name is not UTF-8: {}", path.display()))
            .to_string();
        let id = file_name
            .strip_suffix(".svg")
            .expect("filtered icon path should end with .svg")
            .to_string();
        validate_icon_id(&id, &path);
        let const_name = const_name_for(&id);
        assert!(
            const_names.insert(const_name.clone()),
            "generated icon constant collision: {const_name}"
        );

        icons.push(IconFile {
            id,
            file_name,
            const_name,
        });
    }

    icons.sort_by(|a, b| a.id.cmp(&b.id));
    assert!(!icons.is_empty(), "assets/icons must contain SVG icons");
    icons
}

fn validate_icon_id(id: &str, path: &Path) {
    let mut chars = id.chars();
    let Some(first) = chars.next() else {
        panic!("empty icon id for {}", path.display());
    };
    assert!(
        first.is_ascii_lowercase() || first.is_ascii_digit(),
        "icon id must start with [a-z0-9]: {}",
        path.display()
    );
    assert!(
        chars.all(|ch| ch.is_ascii_lowercase() || ch.is_ascii_digit() || ch == '-'),
        "icon id must be kebab-case ascii: {}",
        path.display()
    );
}

fn const_name_for(id: &str) -> String {
    let mut out = id.replace('-', "_").to_ascii_uppercase();
    if out
        .chars()
        .next()
        .is_some_and(|first| first.is_ascii_digit())
    {
        out.insert_str(0, "ICON_");
    }
    out
}

fn render_asset_table(icons: &[IconFile]) -> String {
    let mut out = String::from("// @generated by gui/build.rs\n");
    out.push_str("pub(crate) static BUILTIN_ICON_ASSETS: &[BuiltinIconAsset] = &[\n");
    for icon in icons {
        let suffix = format!("/../assets/icons/{}", icon.file_name);
        out.push_str(&format!(
            "    BuiltinIconAsset {{ id: {:?}, svg: include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), {:?})) }},\n",
            icon.id, suffix
        ));
    }
    out.push_str("];\n");
    out
}

fn render_name_constants(icons: &[IconFile]) -> String {
    let mut out = String::from("// @generated by gui/build.rs\n");
    for icon in icons {
        out.push_str(&format!(
            "pub const {}: crate::icon::IconName = crate::icon::IconName::new({:?});\n",
            icon.const_name, icon.id
        ));
    }
    out
}
