use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let panels_dir = manifest_dir.join("src").join("panels");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let generated_path = out_dir.join("panels_generated.rs");

    println!("cargo:rerun-if-changed={}", panels_dir.display());

    let mut panel_files = fs::read_dir(&panels_dir)
        .expect("read app/src/panels")
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "rs"))
        .filter(|path| {
            path.file_stem()
                .and_then(|stem| stem.to_str())
                .is_some_and(|stem| stem != "mod" && stem != "generated")
        })
        .collect::<Vec<_>>();
    panel_files.sort();

    let mut generated = String::new();
    generated.push_str("// @generated by app/build.rs\n");
    generated.push_str("use gui::panel::PanelDeclaration;\n\n");

    for path in &panel_files {
        let module = path
            .file_stem()
            .and_then(|stem| stem.to_str())
            .expect("panel file stem must be UTF-8");
        assert!(
            is_rust_identifier(module),
            "panel file `{module}` must be a valid Rust identifier"
        );
        generated.push_str(&format!("#[path = {:?}]\nmod {module};\n", path));
    }

    generated.push_str(
        "\npub(crate) fn collect_panels(ctx: &PanelBuildContext<'_>) -> Vec<PanelDeclaration> {\n",
    );
    generated.push_str("    vec![\n");
    for path in &panel_files {
        let module = path.file_stem().and_then(|stem| stem.to_str()).unwrap();
        generated.push_str(&format!("        {module}::panel(ctx),\n"));
    }
    generated.push_str("    ]\n");
    generated.push_str("}\n");

    fs::write(generated_path, generated).expect("write panels_generated.rs");
}

fn is_rust_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    (first == '_' || first.is_ascii_alphabetic())
        && chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
}
