#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct FrameStats {
    pub widget_build_calls: usize,
    pub tree_nodes: usize,
    pub stable_id_lookups: usize,
    pub full_tree_scans: usize,
    pub reconcile_child_matches: usize,
    pub layout_nodes_visited: usize,
    pub layout_boundaries_flushed: usize,
    pub layout_cache_hits: usize,
    pub layout_cache_misses: usize,
    pub text_measure_calls: usize,
    pub text_layout_requests: usize,
    pub text_layout_cache_hits: usize,
    pub paint_nodes_visited: usize,
    pub paint_commands: usize,
    pub paint_fragments_rebuilt: usize,
    pub paint_fragments_reused: usize,
    pub paint_fragments_evicted: usize,
    pub paint_boundaries_dirty: usize,
    pub paint_fragment_commands_recorded: usize,
    pub paint_composition_fragments_flattened: usize,
    pub paint_order_cache_hits: usize,
    pub paint_order_cache_misses: usize,
    pub full_root_paint_calls: usize,
    pub backend_commands: usize,
    pub text_batches: usize,
    pub render_passes: usize,
    pub endpoint_cache_updates: usize,
    pub hit_order_cache_hits: usize,
    pub hit_order_cache_misses: usize,
}
